### ISSUE TITLE
New Covid Vaccine Apple Wallet Option

### ISSUE THREAD

**Issue by aravindh-j** [justdmitry/PassKitHelper#11]
Hi,

In latest iOS Update 15.1 added the new apple wallet design for COVID 19 Vaccination (https://support.apple.com/en-us/HT212752). Can you please help me to create this Apple Wallet?

**Comment by justdmitry** [comment]
Hi,

Article says that Health app can create such passes, but also it says "Your vaccination card can't be shared" and "The full details of your vaccination card won't be visible until you've authenticated" - I guess it's some special type of pass that you can't create yourself, only Health app can, because I don't see any new info in [pass package public docs](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/Introduction.html).

**Comment by aravindh-j** [comment]
okay, thanks.

is there any possibility to place an image at the bottom of the Generic pass?

**Comment by justdmitry** [comment]
Not sure what image you are talking about. Pass layout depends on pass type, different layout are shown at https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html

If you mean small health icon in white rectangle in lower-left corner - it's a link to linked App (Health in your example), you can set it with `AssociatedStoreIdentifiers` (described in "Associated App Keys" section).
