### ISSUE TITLE
Pass File gets corrupted when updating multiple fields 

### ISSUE THREAD

**Issue by DboukAli98** [justdmitry/PassKitHelper#20]
Hello @justdmitry  , when I attempt to update multiple fields in the pass the pass file gets corrupted , but when I update only one field it goes fine and get updated .

**Comment by justdmitry** [comment]
As soon as "pass file" is regular zip file, and it is delivered to iPhone as a single piece of data, and only phone itself "knows" what fields are updated (by comparing with stored "previous" pass file) - it's impossible to see arriving new file as "broken" or "unbroken" depending of current stored (on iPhone) data.

I think you have some problems with passfile generation process.

Also, as soon as pass file is regular file - you can save it (all versions - "broken" and "valid") to your computer and send them to your phone via whatsapp or telegram or any other file transfer, and see how iPhone understands it.

**Comment by DboukAli98** [comment]
Thanks @justdmitry for your continous help ! Is there a way to make payments through apple wallet store card ?

**Comment by justdmitry** [comment]
There is something called [Rewards Enrollment](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/PassPersonalization.html#//apple_ref/doc/uid/TP40012195-CH12-SW2), but I can't check/test it because I don't have NFC functionality enabled in my account. This is definitely not a "payment" but maybe you can use it somehow.
